version: 2
jobs:
   build:
     docker:
       - image: circleci/node:7.10.0
     steps:
       - checkout
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
       - run:
          name: install-dependencies
          command: 'npm install'
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       - run:
          name: test
          command: npm test
