version: 2
jobs:
   build:
     docker:
       - image: circleci/node:7.10.0
       environment:
          WEATHER_KEY: WEATHER_KEY
     steps:
       - checkout
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: install-dependencies
          command: 'pwd && ls && npm -v && npm install'
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       - run:
          name: test
          command: npm test
