version: 2
jobs:
   build:
     docker:
       - image: circleci/node:7.10.0
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g node:latest-browsers'
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       - run:
          name: test
          command: npm test
